server {
  listen 443 ssl;
  server_name paint.fox.ayu.land;

  ssl_certificate /home/ayu/z-image/foxnn/server.crt;
  ssl_certificate_key /home/ayu/z-image/foxnn/server.key;
  
  location / {
    proxy_pass http://127.0.0.1:26220;
    proxy_redirect default;
    proxy_http_version 1.1;
    proxy_send_timeout 600s;
    proxy_read_timeout 600s;
  }
}
